name: Build and Test on Push

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Run tests
        run: docker-compose -f docker-compose.yml up --abort-on-container-exit

      - name: Build production image
        run: docker-compose -f docker-compose.yml build app

      - name: Push image to Docker Hub
        run: docker-compose -f docker-compose.yml push app
